### ISSUE TITLE
出错

### ISSUE THREAD

**Issue by Admin1531** [Mufanc/iSmartAuto#2]
m298921375@gmail.com,可以联系下嘛

**Comment by 3304366352UESR** [comment]
运行失败

**Comment by Mufanc** [comment]
请详细描述错误信息，谢谢

**Comment by 3304366352UESR** [comment]
代码如下：
C:\iSmartAuto-master>python iSmart.py
Traceback (most recent call last):
  File "C:\iSmartAuto-master\iSmart.py", line 4, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

C:\iSmartAuto-master>pause

**Comment by 3304366352UESR** [comment]
请问是什么问题

**Comment by 3304366352UESR** [comment]
运行run,bat就会出现：
C:\iSmartAuto-master>python iSmart.py
Traceback (most recent call last):
File "C:\iSmartAuto-master\iSmart.py", line 4, in
import requests
ModuleNotFoundError: No module named 'requests'

C:\iSmartAuto-master>pause

**Comment by Mufanc** [comment]
> 请问是什么问题

请您仔细阅读 [README.md](https://github.com/Mufanc/iSmartAuto#readme) 中的内容，使用前首先执行 `pip install -r requirements.txt` 命令安装所有依赖模块

**Comment by 3304366352UESR** [comment]
可是我点击了好多次
pip_install.bat
显示安装了

**Comment by 3304366352UESR** [comment]
但是启动就没如上代码所示

**Comment by 3304366352UESR** [comment]
不知道是什么原因

**Comment by Mufanc** [comment]
你的模块是不是没装到对应版本的 Python 上

**Comment by 3304366352UESR** [comment]
怎么安装

**Comment by Mufanc** [comment]
安装方法自行百度，我只解答与这个仓库相关的问题
